name: Create Development Builds

on:
  push:
    branches: ['master']

jobs:
  build_android:
    type: build # This job type creates a production build for Android
    params:
      platform: android
      profile: development
